### PR TITLE
Adds assets directory and remove CSS inline

### PR DESCRIPTION
**Pull request by mateusortiz**
Remove CSS inline on HTML, and separate the CSS directory in assets.

### CODE REVIEW

**Comment by leo** [comment]
Not necessarily an improvement when it comes to performance (the browser will have to do another HTTP request before it gets the styles), but definitely a great step into the direction of a cleaner structure. 

All in all, I'm 👍 on this though (mostly because it also allows the browser to cache the styles).

**Comment by mateusortiz** [comment]
yay, sometimes it's good to inline css, but is a little bad for maintenance and organization.

With inline css you have a gain in performance, but sometimes it pays not win in performance and lose with organization and modularization.

**Comment by mateusortiz** [comment]
cc // @rauchg

**Comment by rauchg** [comment]
Much cleaner. Thanks @mateusortiz

**Pull request merged**
