### PR TITLE
Move styles into external file and fix HTML

### PR DESCRIPTION
**Pull request by leo**

### CODE REVIEW

**Comment by rauchg** [comment]
I like the inline styles because with a single download we get everything! I would definitely be open to moving it into external files and using a very simple templating library to server-render them embedded in the file.

**Comment by leo** [comment]
@rauchg Have you thought about the caching part?

We had this discussion [earlier](https://github.com/zeit/hyperterm-website/pull/1) and merged the PR because the browser otherwise wouldn't be able to cache the assets (thus leading to increased loading times).

Please also note that this PR contains 4 other important fixes. So generally, I still think this is a better solution than leaving it inline. If you want, I can make a compromise and open another PR later in which I'm going to introduce a build workflow that minifies the CSS.

That would be the perfect combination of both speed and clean code.

**Comment by leo** [comment]
We could also combine that with the awesome technique of only adding the important styles (those that are in the viewport when the site loads) inline and the rest to the external style sheet.

**Comment by leo** [comment]
@rauchg ^

**Pull request closed without merging**
