### PR TITLE
Adds linux downloads link to installation page

### PR DESCRIPTION
**Pull request by chanux**

### CODE REVIEW

**Comment by rauchg** [comment]
Awesome! We need to find a way for that URL to also return the `AppImage`.
We should say `and Linux (deb, AppImage)` so that the user can choose based on format.
The download server is nuts: https://github.com/GitbookIO/nuts
Maybe they have a query parameter we can pass to get each format.
Thank you!

**Comment by chanux** [comment]
I just checked `nuts` documentation. It requires win,mac/osx,linux in [file name](http://nuts.gitbook.com/assets.html). They seem to have automatic platform detection. Anyhow I can't see appimage specific instructions or a workaround to serve appImage file.

**Comment by rauchg** [comment]
:\ I see. In that case maybe we have to query the API and dynamically create links to GitHub instead? We can query `/api/versions` to get the version number.

**Comment by chanux** [comment]
It's possible to query `https://api.github.com/repos/zeit/hyperterm/releases/latest` and pick up the download link to the latest app Image.

IMO we taking it a bit too far. Why not just mention appImage and link to the latest release page?

**Comment by leo** [comment]
@chanux Let's do that!

**Comment by leo** [comment]
IMHO, that's fine for now! We can make this more complex later.

**Pull request merged**
