### PR TITLE
update broken link

### PR DESCRIPTION
**Pull request by Jonahss**

### CODE REVIEW

**Comment by CodeTheory** [comment]
I'm a little confused. `https://github.com/zeit/hyperterm/tree/master/lib/actions` isn't a broken link for me.

**Comment by Jonahss** [comment]
ah, yeah that works. But the current version of the site must be behind. It links to `https://github.com/zeit/hyperterm/tree/master/app/lib/actions` on hyperterm.org.

I didn't bother to correctly check the link I was replacing. sorry.
could use a deploy though?

**Comment by CodeTheory** [comment]
The live version of the site links correctly for me. Also looks like it was fixed on August 2nd. 😄 https://github.com/zeit/hyperterm-website/commit/27e3d1a03e0ce96ae1b373b9bdc6c1cbfed7a4f2

**Comment by Jonahss** [comment]
screen shot 2016-09-13 at 10 28 32 am
I still get a 404 when I click this link. Notice it links to `https://github.com/zeit/hyperterm/tree/master/app/lib/actions` which gets me a 404.

**Pull request closed without merging**
